### ISSUE TITLE
The Start-VM doesn't use the VMName variable (CopyFilesToVM.ps1)

### ISSUE THREAD

**Issue by ilyas-hi** [jamesstringerparsec/Easy-GPU-P#1]
Hello, thanks for your work to begin with. 
I've never tried to enable the GPU on my VMs just because of how difficult it is so your work is great for people like me.
I've just noticed that the vm used in the Start-VM command is hard-coded.

**Comment by jamesstringerparsec** [comment]
Hey, good find, i fixed this, did everything else work?

**Comment by ilyas-hi** [comment]
Almost :) 
At the end everything worked.
But one command in particular was in error,

In the same file, the command "Set-VMFirmware" tries to seek data based on the name ("Where-Object name -like" etc).
The thing is, I'm sure it would have work if my computer was set in english, but it is in french, so it has no luck in finding "Hard drive" as it would translate as "Disque dur".
I'm not used to PS files / syntax so I can't help but tell that perhaps there is another mean to get to the same result, perhaps requesting by the type or something else if it exists...
But it is minor as I said because, even though this command in particular failed, the vm was just working fine and gpu accelerated.

**Comment by jamesstringerparsec** [comment]
I see, well the good news is that line is needed so I removed it.

I have updated the repo to remove it. 

Thank you
