### ISSUE TITLE
Creating a VM with certain (too long?) names will cause Windows 11 to fail to process unattend.xml on startup.

### ISSUE THREAD

**Issue by kitlith** [jamesstringerparsec/Easy-GPU-P#13]
exact error message is as follows:
> Windows could not parse or process unattend answer file [C:\unattend.xml] for pass [specialize]. The answer file is invalid.

The VMName is passed as ComputerName inside the specialize pass, which is why the VMName can affect anything on the VM at all. I suspect what was causing me to run into this issue was that I was using a 20 character long VMName, while Windows has a 15 character limit on NetBIOS names. I cut that down to a 6 character name, which allowed windows to actually finish setting up and boot.

**Comment by jamesstringerparsec** [comment]
You answered your own question, this script doesn't do any parameter pre-checking so if you provide invalid parameters it will fail.

**Comment by kitlith** [comment]
well, it's here if anyone else has this issue now, and i brought it up here in case you wanted to add it as a comment/warning somewhere. the error message that windows gave was not especially helpful...
