### ISSUE TITLE
Got issue with running the script

### ISSUE THREAD

**Issue by Punk3r69** [jamesstringerparsec/Easy-GPU-P#14]
Hi, I got an issue with converting Iso as it says it cannot convert because the path is null. 
![image](https://user-images.githubusercontent.com/36036205/144872016-6cbb235d-3fcc-41ab-b148-bfa212b8852e.png)
and this is what the log says :
![image](https://user-images.githubusercontent.com/36036205/144872168-f1d4d871-f07e-4f0c-b127-f9e0276c952c.png)
The path given is direct to the Iso file.

**Comment by jamesstringerparsec** [comment]
I don't think you correctly provided the file path to the Windows 10/11 ISO file in the script, you need to edit the script and make sure the path to the ISO matches the file path where you downloaded the ISO.

**Comment by jamesstringerparsec** [comment]
Closing this until Punk3r69 replies
