### ISSUE TITLE
Issue with PreChecks script

### ISSUE THREAD

**Issue by genialen** [jamesstringerparsec/Easy-GPU-P#16]
During run of PreCheck script I receive this error message, what this could be?

![image](https://user-images.githubusercontent.com/12430665/145193399-63e3dfa8-0cf1-4634-b319-7536b7b4b39b.png)

**Comment by jamesstringerparsec** [comment]
Likely one of the following things:

1. Your GPU may be too old
2. Your Hyper-V features may not all be fully enabled
3.  Your OS version may be too old

**Comment by genialen** [comment]
Videocard GTX 1660 Super, driver up-to-date, Windows 10 Pro version 21H1

**Comment by jamesstringerparsec** [comment]
Can you please translate the first red line for me?

**Comment by genialen** [comment]
Namespace is not correct.

**Comment by jamesstringerparsec** [comment]
Can you please follow the steps for "Enable the Hyper-V role through Settings" and make sure both Hyper V management tools and Hyper-V platform are ticked, then reboot.

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

**Comment by genialen** [comment]
Thanks a lot, this issue could appear if only this "ticks" were made
![image](https://user-images.githubusercontent.com/12430665/145466587-7b46b81c-1319-48a3-a3d1-a1b0650862c1.png)
The original guide did not include in itself this part
![image](https://user-images.githubusercontent.com/12430665/145466658-a14c2d79-db9a-4b00-887f-f42ad427840f.png)
Completing it was crucial. Now all the Powershell commands work.
