### ISSUE TITLE
Bootable ISO improperly detected as non bootable

### ISSUE THREAD

**Issue by rindoze** [jamesstringerparsec/Easy-GPU-P#18]
Using image Win10_1809Oct_English_x64.iso, the file is bootable. The check in the script was thinking it wasn't causing the script to crash. I just removed the entire else clause to skip this and it worked.
I think the problem lies with the systemDrive parameter. It is setting it as a drive letter that doesn't exist. I am not sure what systemDrive is supposed to represent.

**Comment by jamesstringerparsec** [comment]
1809 isn't supported, please read the entire readme before starting to
experiment with this script.

**Comment by rindoze** [comment]
It behaves the same with Win11_English_x64v1
