### ISSUE TITLE
Resolution locked at 1024x768

### ISSUE THREAD

**Issue by dlbears** [jamesstringerparsec/Easy-GPU-P#21]
First off, thanks for the great work in putting the scripts together!

Now the issue,
I Partitioned a 6800xt, it works (remarkably had 4vms sharing it running the heaven benchmark, held just above 60 at 1080p cranked) and on first boot it starts with a resolution of 1080p, but subsequent boots are locked down to 1024x768

tried so far:
- Set-VMVideo while the vm is off (didn’t work)

spec:
Host and guest os: windows 11
CPU: Ryzen 9 3950x
GPU: Radeon 6800xt

**Comment by dlbears** [comment]
Found a fix for 1080p (the Hyper V  display adapter was disabled)

**Comment by hgouveia** [comment]
> Found a fix for 1080p (the Hyper V display adapter was disabled)

i had the same issue my host video card is a GTX 1060,  i disabled the **Microsoft Hyper-V Video** as suggest by @dlbears , and i was able to changed to 1080p,  i disabled it again, and kept in 1080p 🎉
