### ISSUE TITLE
Windows 20H2 and NVIDIA Quadro T2000 Success

### ISSUE THREAD

**Issue by connorcarnes** [jamesstringerparsec/Easy-GPU-P#22]
Thanks for putting this together! It's worked well for me so far. Sharing my system details so you can have more data. Let me know if I can provide any other useful info.

**System Details**
**Laptop:** Lenovo P17 Gen 1
**GPUs:** NVIDIA Quadro T2000 and Intel(R) UHD Graphics
**Host OS:** Windows 10 Pro Version 20H2 Build 19042.1415
**VM ISO:** [Windows 10 Enterprise Evaluation](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise)

I left the GPUname param as AUTO per the instructions. I noticed the pre reqs mention laptops with NVIDIA cards not being supported so I assumed the integrated graphics would be passed through. But when looking at task manager it definitely looks like the NVIDIA card is being used. Is that expected with Quadro cards?

**Comment by jamesstringerparsec** [comment]
Hi there,

Yes unfortunately in Win10 it picks the NVIDIA GPU as this is optimal for
compute (CUDA etc), but it's not optimal for Parsec.  You'll need to
upgrade to Win11 to select the Intel GPU.

**Comment by connorcarnes** [comment]
Ah ok then, I'll close this out. Thanks!

**Comment by Snuupy** [comment]
@connorcarnes Any updates on this? If you pass through the intel GPU does that mean you don't get to use the NVIDIA one? I see in BIOS you can select "discrete" which disables the igpu and permanently uses the dgpu (Quadro). Does this change anything/help at all?
