### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by Its-MS** [jamesstringerparsec/Easy-GPU-P#25]
I ran the file and it came up with the above error, no idea what the actual issue is though, any help would be appreciated. 
![Error](https://user-images.githubusercontent.com/97409959/148700072-b91fcb06-5e8b-46ed-8183-85b5f03b394a.png)

**Comment by jamesstringerparsec** [comment]
Please visit the log folder listed in the ERROR line, within the folder there will be a log file.  Please paste the contents here.

**Comment by Its-MS** [comment]
So I got, 
Initializing wimgapi.
Shutting down wimgapi.
From DismLogs.log

And I got this, 
**********************
Windows PowerShell transcript start
Start time: 20220109203815
Username: MAUROSPC\msous
RunAs User: MAUROSPC\msous
Configuration Name: 
Machine: MAUROSPC (Microsoft Windows NT 10.0.22000.0)
Host Application: C:\Windows\syswow64\WindowsPowerShell\v1.0\PowerShell_ISE.exe
Process ID: 13924
PSVersion: 5.1.22000.282
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22000.282
BuildVersion: 10.0.22000.282
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
INFO   : Opening ISO Win11_English_x64.iso...
INFO   : Looking for M:\sources\install.wim...
INFO   : Looking for the requested Windows image in the WIM file
INFO   : Image 6 selected (Professional)...
INFO   : Creating sparse disk...
INFO   : Mounting VHDX...
INFO   : Initializing disk...
INFO   : Creating EFI system partition...
INFO   : Formatting system volume...
INFO   : Setting system partition as ESP...
INFO   : Creating MSR partition...
INFO   : Creating windows partition...
INFO   : Formatting windows volume...
INFO   : Windows path (T:) has been assigned.
INFO   : Windows path (T:) took 1 attempts to be assigned.
INFO   : System volume location: S:
INFO   : Applying image to VHDX. This could take a while...
INFO   : Image was applied successfully.
INFO   : Applying unattend file (autounattend.xml)...
INFO   : Making image bootable...
PS>TerminatingError(Start-Process): "This command cannot be run due to the error: The system cannot find the file specified."
>> TerminatingError(Start-Process): "This command cannot be run due to the error: The system cannot find the file specified."
ERROR  : This command cannot be run due to the error: The system cannot find the file specified.
INFO   : Log folder is C:\Users\msous\AppData\Local\Temp\Convert-WindowsImage\611fb555-bb24-43f2-88c9-91912a97a657
INFO   : Closing Windows image...
INFO   : Closing ISO...
INFO   : Done.
**********************
Windows PowerShell transcript end
End time: 20220109203956
**********************


Hope either help. Ta

**Comment by jamesstringerparsec** [comment]
Is this some kind of leaned out version of Windows 10 that has a bunch of stuff removed?

**Comment by Its-MS** [comment]
So its windows 11 and I ran the debloat software, however, I have closed powershell and re-opened it, it seems to have somehow worked now??!!

**Comment by jamesstringerparsec** [comment]
OK, if it's working you're welcome to close this issue.

**Comment by Its-MS** [comment]
Awesome, Thank you!!
