### ISSUE TITLE
Couldn't find path

### ISSUE THREAD

**Issue by csupi003** [jamesstringerparsec/Easy-GPU-P#27]
Hi, 
I got the following error in PS:

INFO   : Opening ISO Win11_English_x64.iso...
INFO   : Looking for E:\sources\install.wim...
INFO   : Looking for the requested Windows image in the WIM file
INFO   : Image 6 selected (Professional)...
INFO   : Creating sparse disk...
INFO   : Mounting VHDX...
INFO   : Initializing disk...
INFO   : Creating EFI system partition...
INFO   : Formatting system volume...
INFO   : Setting system partition as ESP...
INFO   : Creating MSR partition...
INFO   : Creating windows partition...
INFO   : Formatting windows volume...
INFO   : Windows path (H:) has been assigned.
INFO   : Windows path (H:) took 1 attempts to be assigned.
INFO   : System volume location: F:
INFO   : Applying image to VHDX. This could take a while...
INFO   : Image was applied successfully. 
INFO   : Applying unattend file (autounattend.xml)...
INFO   : Making image bootable...
INFO   : Drive is bootable.  Cleaning up...
INFO   : Finding and copying driver files for AMD Radeon RX 5600 XT to VM. This could take a while...
INFO   : Setting up Parsec to install at boot
INFO   : Dismounting VHDX...
INFO   : Closing Windows image...
INFO   : Closing ISO...
INFO   : Done.
New-VM : Nem sikerült új virtuális gépet létrehozni.
A(z) GPUP konfigurációjának életbe léptetése nem sikerült. (Virtuális gép azonosítója: FD3C3797-7F9E-438C-86FE-EDDBEA4AB9F6)
Nem sikerült a konfigurációs adattároló elérése: A rendszer nem találja a megadott elérési utat. (0x80070003).
At C:\Users\Olivér\Downloads\Easy-GPU-P-main (1)\Easy-GPU-P-main\CopyFilesToVM.ps1:4304 char:9
+         New-VM -Name $VMName -MemoryStartupBytes $MemoryAmount -VHDPa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.NewVM
.....

Just a quick translate: 
Couldn't create VM. Couldn't reach the config storage. Couldn't find the path. 

I tried it with different Win10 & 11 versions.

**Comment by jamesstringerparsec** [comment]
I don't think you enabled hyper-v in Windows properly

**Comment by csupi003** [comment]
Thanks for the hint. Still not working but it should be something with Hyper-v.
