### ISSUE TITLE
Request: Support for Linux Hosts

### ISSUE THREAD

**Issue by Daasin** [jamesstringerparsec/Easy-GPU-P#28]
As stated in title, can support be added for this to work with the 5.16 Linux Kernel? 

Which also supports Hypervisors & Para-virtualization features, it can also passthrough, have nested virtualisation, run VMware, Virtualbox, QEMU+KVM, Xen, Rump vKernels, Run from Containers, Use Wine/Darwine, etc etc etc 

Surely if people can run online games in Guest VM's then this would be possible to do on there: https://www.youtube.com/watch?v=Bc3LGVi5Sio  right?

**Comment by jamesstringerparsec** [comment]
There are no plans to add support for Linux hosts.  You should look at LibVF.IO if you are wanting a somewhat similar solution on Linux hosts.

**Comment by Daasin** [comment]
Just realized a similar issue #26  was filed mid way through typing this, my apologies for the duplicate @jamesstringerparsec

**Comment by cyberquarks** [comment]
Hi @Daasin issue #26 is quite different, what you mentioned here is Linux Host, but 26 is still Windows 11 host with Linux guest VM, unless you mean the same stack as what I posted in a comment there.
