### ISSUE TITLE
Increase GPU resources

### ISSUE THREAD

**Issue by maaa3** [jamesstringerparsec/Easy-GPU-P#280]
I want to allocate more resources to the virtual GPU. How do i do this, without recreating your VM? Thanks.

**Comment by mitchellurgero** [comment]
I've not really tested but this might work:

```powershell
$VMName = "game"
$GPUResourceAllocationPercentage = 80
[float]$devider = [math]::round($(100 / $GPUResourceAllocationPercentage),2)
Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionVRAM ([math]::round($(1000000000 / $devider))) -MaxPartitionVRAM ([math]::round($(1000000000 / $devider))) -OptimalPartitionVRAM ([math]::round($(1000000000 / $devider)))
Set-VMGPUPartitionAdapter -VMName $VMName -MinPartitionEncode ([math]::round($(18446744073709551615 / $devider))) -MaxPartitionEncode ([math]::round($(18446744073709551615 / $devider))) -OptimalPartitionEncode ([math]::round($(18446744073709551615 / $devider)))
Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionDecode ([math]::round($(1000000000 / $devider))) -MaxPartitionDecode ([math]::round($(1000000000 / $devider))) -OptimalPartitionDecode ([math]::round($(1000000000 / $devider)))
Set-VMGpuPartitionAdapter -VMName $VMName -MinPartitionCompute ([math]::round($(1000000000 / $devider))) -MaxPartitionCompute ([math]::round($(1000000000 / $devider))) -OptimalPartitionCompute ([math]::round($(1000000000 / $devider)))



```

Save to a powershell script, run as admin.

**Comment by Daviddbalaban** [comment]
Hello , 
this does not work .... 

I have an rtx 4090 and I have tried both 10% and 90% and getting the same gpu score on this test :

https://www.matthew-x83.com/online/gpu-benchmark-test.php

any idea ?

**Comment by mitchellurgero** [comment]
> Hello , this does not work ....
> 
> I have an rtx 4090 and I have tried both 10% and 90% and getting the same gpu score(1280) on this test :
> 
> https://www.matthew-x83.com/online/gpu-benchmark-test.php
> 
> any idea ?
> 
> Thanks in advance

Did you make sure that the test used your actual GPU and not CPU? Browser acceleration, which that test uses, probably cannot use the GPU in a passthrough capacity or there is a different underlying issue.

So this does work as confirmed by multiple other users, but something else is going on for you. I bet browser acceleration is broken in someway. Try doing this and turning on hardware acceleration in the browser:

https://github.com/jamesstringerparsec/Easy-GPU-PV/issues/304#issuecomment-1670572182

**Comment by Zora-Z0** [comment]
Hello, does anyone know how you would increase the CPU Cores?

**Comment by mitchellurgero** [comment]
> Hello, does anyone know how you would increase the CPU Cores?

If the VM is made already, right click the VM and go into the settings to adjust the core count.
