### ISSUE TITLE
VHD Path

### ISSUE THREAD

**Issue by YanisBDF** [jamesstringerparsec/Easy-GPU-P#29]
Hello can you take Hyper-V Manager's VHD Path instead of hardcoding it ?
Or at least maybe add it so we can see and modify it in CopyFilesToVM.ps1's parms
This could be more "user friendly" if we want to install the VM in a different drive

Thank you !

**Comment by jamesstringerparsec** [comment]
yep, a few others have asked for it and it's not difficult, I'll take care of it in the next few days.

**Comment by jamesstringerparsec** [comment]
This has been released, please re-download the zip file from https://github.com/jamesstringerparsec/Easy-GPU-P/archive/refs/heads/main.zip
