### ISSUE TITLE
copy-item : There is not enough space on the disk.

### ISSUE THREAD

**Issue by derpyderp123** [jamesstringerparsec/Easy-GPU-P#38]
How much space do I need.. I have 50 gigs on my C drive

-----------------------
INFO   : Setting up Parsec to install at boot
ERROR  : There is not enough space on the disk.

INFO   : Log folder is C:\Users\alfre\AppData\Local\Temp\Convert-WindowsImage\34ef08de-218b-4971-a08d-76e38240d804
INFO   : Closing Windows image...
INFO   : Closing ISO...
INFO   : Done.
Failed to create VHDX, stopping script

PS C:\Users\alfre\Downloads\Easy-GPU-P-main> C:\Users\alfre\Downloads\Easy-GPU-P-main\PreChecks.ps1
System Compatible
Printing a list of compatible GPUs...May take a second
Copy the name of the GPU you want to share...
NVIDIA GeForce RTX 3070
NVIDIA GeForce RTX 3070
Press Enter to Exit: 

PS C:\Users\alfre\Downloads\Easy-GPU-P-main> C:\Users\alfre\Downloads\Easy-GPU-P-main\CopyFilesToVM.ps1

Windows(R) Image to Virtual Hard Disk Converter for Windows(R) 10
Copyright (C) Microsoft Corporation.  All rights reserved.
Version 10.0.14278.1000.amd64fre.rs1_es_media.160201-1707

INFO   : Opening ISO win11.iso...
INFO   : Looking for E:\sources\install.wim...
INFO   : Looking for the requested Windows image in the WIM file
INFO   : Image 6 selected (Professional)...
INFO   : Creating sparse disk...
INFO   : Mounting VHDX...
INFO   : Initializing disk...
INFO   : Creating EFI system partition...
INFO   : Formatting system volume...
INFO   : Setting system partition as ESP...
INFO   : Creating MSR partition...
INFO   : Creating windows partition...
INFO   : Formatting windows volume...
INFO   : Windows path (J:) has been assigned.
INFO   : Windows path (J:) took 1 attempts to be assigned.
INFO   : System volume location: I:
INFO   : Applying image to VHDX. This could take a while...
INFO   : Image was applied successfully. 
INFO   : Applying unattend file (autounattend.xml)...
INFO   : Making image bootable...
INFO   : Drive is bootable.  Cleaning up...
INFO   : Finding and copying driver files for NVIDIA GeForce RTX 3070 to VM. This could take a while...
Copy-item : There is not enough space on the disk.
At C:\Users\alfre\Downloads\Easy-GPU-P-main\Add-VMGpuPartitionAdapterFiles.psm1:36 char:17
+ ...             Copy-item -path "$ServiceDriverDir" -Destination "$Servic ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (nvui.dll:FileInfo) [Copy-Item], IOException
    + FullyQualifiedErrorId : CopyDirectoryInfoItemIOError,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by jamesstringerparsec** [comment]
You need however much you set in "SizeBytes" in the params section of copyfilestovm.ps1

**Comment by derpyderp123** [comment]
> You need however much you set in "SizeBytes" in the params section of copyfilestovm.ps1

ive set it as SizeBytes  = 10GB

**Comment by jamesstringerparsec** [comment]
Make the disk bigger, you need minimum 20GB

**Comment by derpyderp123** [comment]
> Make the disk bigger, you need minimum 20GB

fixed
