### ISSUE TITLE
image conversion fails with Windows 10 21H2 Media

### ISSUE THREAD

**Issue by gawainXX** [jamesstringerparsec/Easy-GPU-P#4]
Fails to convert image when supplied with the 21H2 media which uses ESD format for install instead of install.wim

{{DriveLetter}}\Sources\Install.wim isn't present with 21H2,, it's instead in ESD format
{{DriveLetter}}\Sources\Install.esd

I tried to make a couple of adjustments to the script however a fair portion of the script works on the assumption it's working with install.wim so I was not able to easily adapt it.

Would it be possible to add support for install.esd, as well as potentially modularize some of the larger portions of the script such as the conversion logic?

As a workaround I was able to use Rufus to download Windows 21H1 from Microsoft Servers

**Comment by jamesstringerparsec** [comment]
I'm using 21H2 and couldn't reproduce this, make sure you're downloading the ISO directly from the website listed in the readme and not using the Windows Media Creation Tool

**Comment by jagarop** [comment]
> I'm using 21H2 and couldn't reproduce this, make sure you're downloading the ISO directly from the website listed in the readme and not using the Windows Media Creation Tool

yes, the issue was caused by downloading ISO using the Windows Media Creation Tool.

regular iso downloaded from microsoft **without** using their tool still have "\sources\install.wim" even in lastest current 21H2 version.

**Comment by jagarop** [comment]
Btw, it looks like you're forced to use the Windows Media Creation Tool if the browser reports to website it's running in Windows.

**Comment by gawainXX** [comment]
I can confirm, I'm able to access the direct download for the .ISO on Android or Linux, but when using windows I couldn't find a way to access the download directly without using the tool.

I can confirm that when I had downloaded the .ISO file directly on a Linux system, without using the tool, the .\sources\install.wim file was present.

Perhaps there might be a way to force the site to present the .ISO when running on windows such as changing user agent settings on browser? (Although this starts to venture outside of the intended simplicity of this package).

It does appear that you can also download the 21H2 .ISO file directly using a tool such as Rufus.

**Comment by gawainXX** [comment]
So far the easiest and most reliable method I've found is to use Rufus to download to 21H1 ISO file.

Link to a guide for that;
https://www.nextofwindows.com/downloading-windows-10-iso-images-using-rufus

There are other options such as manually changing the user agent, starting a web browser using a useragent command line parameter, or a fairly complex powershell script which does an invoke-webrequest (and is subject to breaking),

But by far the Rufus method is one that I feel is fairly easy and comfortable passing along instructions for to non highly-technical people.

**Comment by gawainXX** [comment]
I have a pending pull request which expands upon the ISO download pre requisite as it seems to be common people are trying to use an ISO downloaded via the Microsoft tool which won't seemingly work without a significant code alteration l.

**Comment by gawainXX** [comment]
Readme was updated
