### ISSUE TITLE
MMIO Region Above Supported Physical Address Range.

### ISSUE THREAD

**Issue by PotatoeShaman** [jamesstringerparsec/Easy-GPU-P#40]
My VM will fail to start giving an MMIO error. A small bit of research suggests this could be an incompatibility with older CPU architectures, as I am running an I7-2600k (Sandy Bridge). 
This issue thread ( [https://github.com/microsoft/wslg/issues/33] ) on WSL highlights that these older chips only support 36bit physical addresses. 
I don't have much knowledge in this area but I hope its something that can be supported in future releases of Easy-GPU-P.
![Capture](https://user-images.githubusercontent.com/26376359/148756188-2ddce529-234d-4c5b-9585-bd1d4e96ce2c.PNG)
PC Details (If Important):
I7-2600k
24GB DDR3
GTX 1080
1TB SSD w/ 200GB free space
Win 10 21H1 x64

VM Preset:
SizeBytes = 40GB
MemoryAmount = 8GB
CPUCores = 2
GPUAllocation = 50
ISO = Win 10 21H1 x64

**Comment by dhgouveia2** [comment]
I had the same issue, I've found this thread https://www.reddit.com/r/HyperV/comments/nfhrqx/hyperv_gpup_mmio_error/ where they suggets to use `Set-VM -HighMemoryMappedIoSpace 512MB -VMName $vm` , it worked for me

**Comment by amo42** [comment]
This also happens to my older Ivy Bridge 3570k. Setting the Max MMIO to 512 MB solved, but doesn't would that mean, the vm only have 512 MB of graphic memory?

**Comment by PotatoeShaman** [comment]
@amo42 That is not the case. The amount of GPU memory assigned to the VM is dictated by how many instances you are partitioning said GPU into. If the GPU memory did not get evenly divided amongst them the VM's would not start.

MMIO is memory allocated for input/output for peripheral devices, such as the CPU sending (inputting) frame draw calls to the GPU and the GPU returning (outputting) finished frames.

(I'm not an expert on any of this so take my explanations lightly)

By chance if you open device manager in your VM does your graphics card have a code 43 error?

**Comment by amo42** [comment]
@PotatoeShaman thanks for the insights. I didn't have the technical background to understand all the details.

But yes, I've got the error code 43 as well. Currently, I'm thinking it comes from the OS mismatch. I'm running win11 on a win10 host. So I'll spin up another VM with Win10 both, and check if the driver works here.

**Comment by PotatoeShaman** [comment]
@amo42 Ah, well I hope that will do it for you and update here if it does, but it's possible our old CPU's aren't capable of this technology. 

My host and client are identical versions of windows yet I too have code 43. I've spend the last day attempting different fixes and techniques but haven't fount a working one yet.

If anyone with an Ivy/Sandy Bridge CPU happens to read this and doesn't have a Code 43 error please lend some insight into your setup and the technique you used to install GPU-P.

**Comment by amo42** [comment]
@PotatoeShaman could you let us know what you've already tried?

E.g. putting the card into a 4x slot and not the 16x PCIe slot? (found here: [Nvidia-GTX-1650-Code-43-after-VM-reboot](https://communities.vmware.com/t5/ESXi-Discussions/Nvidia-GTX-1650-Code-43-after-VM-reboot/m-p/2882614))

I also wonder why the graphics driver from NVIDIA could not be installed manually within the vm. It claims the Windows version of the VM is not compatible with the selected driver, also, no graphics card could be found.

**Comment by PotatoeShaman** [comment]
I can attempt that PCI slot fix tomorrow.
From my understanding the partitioning works using a special Microsoft display adapter that talks to the host GPU. The VM doesn't directly access the GPU, but that special adapter needs the exact same driver files as the host in order to  talk with the hosts GPU. That behavior explains why the VM would find no compatible GPU because it's not actually present, it's more of a virtual representation of the GPU. 

I'll compile a list of my attempts with links to their sources tomorrow, in case they might work for someone else.

**Comment by jabza** [comment]
Ran into the same issue. (I'm on IvyBridge) I tried the PCI-E switch to a 4x slot but still getting Code 43. I have to use the 512MB fix to even get that far. Very much a head scratcher. Any ideas or is it time I upgraded my CPU...

**Comment by Flamity** [comment]
I'm having the EXACT SAME ISSUE! I'm on an Intel Core i7 2600 CPU, and I get that stupid MMIO error every time. I found out about the 512MB crap but every time I FINALLY boot into the OS, I check my devices and my GTX 1050ti is getting error 43. 

I posted my issue at #153. This is actually so annoying I've spent hours and nothing.. is there any way the software can be changed to accommodate these older processors? @Kodikuu

**Comment by Kodikuu** [comment]
> is there any way the software can be changed to accommodate these older processors?

The 'software' is actually a feature of Windows. All this (Easy-GPU-PV) does is automagically set it up for you. 

The issue you are all having is that your CPUs only support up to 36-bit physical addresses. I'm afraid there is no solution other than a newer PC/CPU that supports bigger physical addresses

**Comment by CyberFIowey** [comment]
I have an AMD GPU, can I set the maximum above 512, I have an rx460?
