### ISSUE TITLE
How to install VM to other drive?

### ISSUE THREAD

**Issue by thijsi123** [jamesstringerparsec/Easy-GPU-P#43]
How do I install the VM to my D drive instead of C drive?

**Comment by ExtremeGrief** [comment]
Search for VMPath variable

**Comment by jed214** [comment]
I think in hyperv you can just turn it off and copy to the other drive the vhdx file, then edit the vm in hyperv selecting the new vhdx location and it should all work. Hope it helps at least as a workaround.

**Comment by thijsi123** [comment]
> Search for VMPath variable

Where can I find that?



> I think in hyperv you can just turn it off and copy to the other drive the vhdx file, then edit the vm in hyperv selecting the new vhdx location and it should all work. Hope it helps at least as a workaround.

I'll try it out as secondary solution thank you.

**Comment by jamesstringerparsec** [comment]
This has been released, please re-download the zip file from https://github.com/jamesstringerparsec/Easy-GPU-P/archive/refs/heads/main.zip
