### ISSUE TITLE
Import Modules not importing correctly

### ISSUE THREAD

**Issue by powerhungryring** [jamesstringerparsec/Easy-GPU-P#48]
Hello I am receiving these errors after running the "CopyFilesToVM.ps1" Here is the error(s) I am getting:
https://pastebin.com/76yXH1D7 
What I have done to troubleshoot is created an Environment Variable  under PSModulePath I added a direct path to the Easy-GPU-P-main folder to see if that would fix my issue.
I verified Hyper-V is installed and active on bios and windows 
My OS is Windows 10 Pro, version 21H2 
Thanks for any assistance

**Comment by jamesstringerparsec** [comment]
When you extract the zip file, do not move files around/ copy them elsewhere, open copyfilestovm.ps1 in Powershell ise from within the folder.
