### ISSUE TITLE
GPU not working in Device Manager

### ISSUE THREAD

**Issue by ichinoboy** [jamesstringerparsec/Easy-GPU-P#51]
I get this error in Device Manager for AMD RX 5600 XT. No idea what's causing the issue. Any help would be appreciated.
![image](https://user-images.githubusercontent.com/97498776/148885990-822701b1-32e5-4c62-a471-052d37a669c2.png)

**Comment by jamesstringerparsec** [comment]
Did you upgrade the AMD driver on the host after running this script?

**Comment by PotatoeShaman** [comment]
I also have a Code 43 Error with my GTX 1080 (497.29 Drivers). I updated my host to these drivers before ever running the script. I will mention that I had to set my HighMemoryMappedIOSpace to 512MB because of my older CPU. I don't know if this has an effect on the operation of this program, maybe someone who can run the default 32GB could try making a 512MB VM and report. (Running 21H1 on both host and client)

**Comment by jamesstringerparsec** [comment]
@PotatoeShaman I believe your older CPU is what is preventing it working for you specifically.

**Comment by PotatoeShaman** [comment]
> @PotatoeShaman I believe your older CPU is what is preventing it working for you specifically.
That's a shame to hear, I was hoping this I7-2600k had some more kick left in it. Is there anything you could possibly think of to have me to try?

**Comment by ichinoboy** [comment]
My host drivers is updated before I ran the script and no update was done on the host afterwards. I did try to run this script to to Update-VMGpuPartitionDriver.ps1 without issues but that did not fix Code 43. My host driver version is 30.0.14011.3017 while the VM is 10.0.19041.1. I'm running 21H1 on both host and VM.

**Comment by jamesstringerparsec** [comment]
I have a 5700XT and it works fine, I am using Win11 but I don't know if that would make any difference.

**Comment by thijsi123** [comment]
The First time I did this via a youtube video https://www.youtube.com/watch?v=XLLcc29EZ_8&t=1313s
and everything worked fine.
I then deleted the VM and never got it to work, always error 43.
GTX 1650.

**Comment by hysel** [comment]
> I have a 5700XT and it works fine, I am using Win11 but I don't know if that would make any difference.

@jamesstringerparsec did you had any problems like error code 31?

**Comment by ichinoboy** [comment]
It works now. For whatever reason, Freesync messed up with my setup with severe artifacts and eventually the device gets disabled automatically. Disabling it seems to have fixed the issue. I've switched to Win11 as well.

**Comment by hysel** [comment]
> It works now. For whatever reason, Freesync messed up with my setup with severe artifacts and eventually the device gets disabled automatically. Disabling it seems to have fixed the issue. I've switched to Win11 as well.

Do I need to re-install the machines after disabling FreeSync? because if not, this is still happening to me when trying to install the latest version of the drivers on the VM (should I even do that BTW)?

**Comment by PotatoeShaman** [comment]
@hysel no you should not be installing the drivers on the VM in the conventional manner. You need to copy your driver files directly from your host machine to the same location on the VM, creating any missing folders along the way. 
If you are running the 'CopyFilesToVm.ps1' script you shouldn't have to do anything driver related on the VM. 
It's important that before running any of the poewershell scripts you need to first run the command
"Set-ExecutionPolicy unrestricted" or else the scripts will not have the authority to perform their tasks properly

**Comment by hysel** [comment]
> @hysel no you should not be installing the drivers on the VM in the conventional manner. You need to copy your driver files directly from your host machine to the same location on the VM, creating any missing folders along the way. If you are running the 'CopyFilesToVm.ps1' script you shouldn't have to do anything driver related on the VM. It's important that before running any of the poewershell scripts you need to first run the command "Set-ExecutionPolicy unrestricted" or else the scripts will not have the authority to perform their tasks properly

Thanks!, I can confirm that everything is working fantastic!
