### ISSUE TITLE
GPU issue

### ISSUE THREAD

**Issue by dilllxd** [jamesstringerparsec/Easy-GPU-P#52]
Everything seemingly worked while installing, I had no errors or anything but after install my graphics card is running Microsoft drivers according to Device Manager. I tried to fix this by reinstalling nvidia drivers on my host machine, rebooting, and then running the Update-VMGpuPartitionDriver.ps1 file. It ran fine with no errors but I still don't see the proper driver installed.

Specs:
Ryzen 7 3700X
32GB Ram
RTX 3060
Windows 11 Pro 21H2

VM:
4 Cores
8GB Ram
50% of AUTO (RTX 3060)
Windows 11 Pro 21H2

EDIT: After doing some looking into it, I think it might be because the VM does not have a "nv_dispi..." directory in C:\Windows\System32\DriverStore\FileRepository and the host does. But, I could be completely wrong I don't know this stuff lol.

**Comment by jamesstringerparsec** [comment]
As long as the device shows no errors in device manager it's working, GPU-P VMs don't use the NVIDIA driver but instead use a microsoft driver that talks directly to the NVIDIA driver on the host.
