### ISSUE TITLE
SizeBytes Parameter is ignored, Virtual Disk is always 25GB

### ISSUE THREAD

**Issue by gawainXX** [jamesstringerparsec/Easy-GPU-P#6]
Virtual Disk is always 25GB in size, there appears to be logic in the script which overrides the parameter set in the beginning of the script.

I.E. I can specify
SizeBytes = 120gb 

but the virtual disk will still be 25GB, leaving little free space for games, requiring manual resizing afterwards.

**Comment by jamesstringerparsec** [comment]
Fixed in [47ac9e9f86f2e0bae1ff8a29c26753fcd6221191](https://github.com/jamesstringerparsec/Easy-GPU-P/commit/47ac9e9f86f2e0bae1ff8a29c26753fcd6221191)
