### ISSUE TITLE
AMD Ryzen: VM will not start if -ExposeVirtualizationExtensions=True

### ISSUE THREAD

**Issue by gawainXX** [jamesstringerparsec/Easy-GPU-P#7]
The Hyper-V VM will fail to power on on AMD Ryzen Systems if the following line is processed.
```Set-VMProcessor -VMName $VMName -ExposeVirtualizationExtensions $true```

The result is that the VM will fail to power on, starting an error that the platform does not support nested virtualization.

This was encountered on an AMD Ryzen 1700X running 21H2

Google searches suggest this might be resolved in an eventual Windows 10 build update, as support is partially available  if the host is running the most current insider preview and the VM is provisioned using version 9.3 configuration.

Can the line ```Set-VMProcessor -VMName $VMName -ExposeVirtualizationExtensions $true``` be commented out or be made conditional depending upon current Nested virtualization support?

**Comment by jamesstringerparsec** [comment]
In Hyper-V, what Configuration version does your VM list as?

**Comment by jagarop** [comment]
> In Hyper-V, what Configuration version does your VM list as?

he was testing in my machine, it lists as 9.0

**Comment by jamesstringerparsec** [comment]
OK, I found the issue.  AMD CPU's don't support Nested Virtualization in Windows 10.  I have fixed the issue by not enabling the function if it's AMD and Windows 10 so I'll close this.

**Comment by gawainXX** [comment]
@jamesstringerparsec 

There might be a bug in the logic,

Get-CimInstance -ClassName Win32_Processor | select Manufacturer
Should probably be 
Get-CimInstance -ClassName Win32_Processor | select -expandproperty Manufacturer

Either that or you'd have to compare $CPUManufacturer.Manufacturer

Example:

```
PS C:\Users\kiyot> $CPUManufacturer =  Get-CimInstance -ClassName Win32_Processor | select Manufacturer
PS C:\Users\kiyot> if ($CPUManufacturer -eq "GenuineIntel"){echo "hello world"}
PS C:\Users\kiyot> $CPUManufacturer =  Get-CimInstance -ClassName Win32_Processor | select -expandproperty Manufacturer
PS C:\Users\kiyot> if ($CPUManufacturer -eq "GenuineIntel"){echo "hello world"}
hello world
```

**Comment by gawainXX** [comment]
Looks like code was adjusted in latest commit and is now,
  $CPUManufacturer = Get-CimInstance -ClassName Win32_Processor | Foreach-Object Manufacturer
